language: python
python:
 - "3.4"

env:
 - AIO_BUILD=master
 - AIO_BUILD=pypi

install:
 - pip install -r travis/requirements-$AIO_BUILD.txt

before_script:
 - wget https://raw.githubusercontent.com/phlax/aio/master/travis/aio.conf

script: aio test
